// =============================================================
// CATÁLOGO DE ITENS — sugestões do "teclado inteligente".
//
// Regras de ouro:
// 1. CATEGORIA sempre uma das 8 REAIS do app (genéricas, servem pra QUALQUER
//    local — casa, apê, praia, veraneio, empresa, loja, escritório):
//    Alimentos · Limpeza · Higiene · Pet · Bebê · Farmácia · Escritório / Empresa · Outros
//    (NUNCA prender um item a um local — ex.: Achocolatado é Alimentos, não "Empresa".)
// 2. `aliases` = como as pessoas DIGITAM de verdade (apelidos, marcas, variações).
//    Acento já é ignorado automaticamente na busca — não precisa repetir sem acento.
// 3. Catálogo LOCAL (sem IA/internet) = instantâneo, offline, nunca inventa.
//    Quanto mais item/apelido, mais cômodo pro usuário. Pode crescer à vontade.
// =============================================================

export type SuggestedItem = { name: string; category: string; aliases?: string[] };

// Atalhos das 8 categorias reais (evita erro de digitação no nome).
const A = "Alimentos";
const L = "Limpeza";
const H = "Higiene";
const P = "Pet";
const B = "Bebê";
const F = "Farmácia";
const E = "Escritório / Empresa";
const O = "Outros";

export const SUGGESTED_ITEMS: SuggestedItem[] = [
  // ─────────────────── ALIMENTOS ───────────────────
  // Básicos / grãos
  { name: "Arroz", category: A },
  { name: "Arroz integral", category: A },
  { name: "Feijão", category: A },
  { name: "Feijão preto", category: A },
  { name: "Feijão carioca", category: A },
  { name: "Lentilha", category: A },
  { name: "Grão de bico", category: A },
  { name: "Açúcar", category: A },
  { name: "Açúcar mascavo", category: A },
  { name: "Adoçante", category: A, aliases: ["adocante"] },
  { name: "Sal", category: A },
  { name: "Sal grosso", category: A },
  { name: "Óleo", category: A, aliases: ["oleo de soja"] },
  { name: "Azeite", category: A, aliases: ["azeite de oliva"] },
  { name: "Vinagre", category: A },
  { name: "Farinha de trigo", category: A, aliases: ["farinha"] },
  { name: "Farinha de mandioca", category: A },
  { name: "Farofa pronta", category: A, aliases: ["farofa"] },
  { name: "Fubá", category: A },
  { name: "Amido de milho", category: A, aliases: ["maizena"] },
  { name: "Aveia", category: A },
  { name: "Granola", category: A },
  { name: "Tapioca", category: A, aliases: ["goma de tapioca"] },
  { name: "Polvilho", category: A },
  // Padaria / massas
  { name: "Pão", category: A },
  { name: "Pão de forma", category: A },
  { name: "Pão francês", category: A, aliases: ["paozinho"] },
  { name: "Pão de hambúrguer", category: A },
  { name: "Pão de alho", category: A },
  { name: "Torrada", category: A },
  { name: "Bolacha água e sal", category: A, aliases: ["biscoito agua e sal", "cream cracker"] },
  { name: "Biscoito", category: A, aliases: ["bolacha"] },
  { name: "Biscoito recheado", category: A, aliases: ["bolacha recheada"] },
  { name: "Macarrão", category: A },
  { name: "Macarrão instantâneo", category: A, aliases: ["miojo", "lamen"] },
  { name: "Lasanha", category: A },
  { name: "Nhoque", category: A },
  // Molhos / temperos
  { name: "Molho de tomate", category: A, aliases: ["molho tomate"] },
  { name: "Extrato de tomate", category: A, aliases: ["massa de tomate"] },
  { name: "Maionese", category: A, aliases: ["hellmanns"] },
  { name: "Ketchup", category: A, aliases: ["catchup"] },
  { name: "Mostarda", category: A },
  { name: "Molho shoyu", category: A, aliases: ["shoyu", "molho de soja"] },
  { name: "Molho inglês", category: A },
  { name: "Vinagrete", category: A },
  { name: "Tempero pronto", category: A, aliases: ["tempero", "caldo", "knorr", "sazon"] },
  { name: "Orégano", category: A },
  { name: "Pimenta do reino", category: A, aliases: ["pimenta"] },
  { name: "Colorau", category: A, aliases: ["colorifico"] },
  { name: "Cominho", category: A },
  { name: "Canela", category: A },
  { name: "Alho", category: A },
  { name: "Cebola", category: A },
  // Café / bebidas quentes
  { name: "Café", category: A },
  { name: "Café em cápsula", category: A, aliases: ["capsula de cafe", "capsula"] },
  { name: "Filtro de café", category: A, aliases: ["filtro de papel", "filtro para cafeteira", "filtro cafeteira", "coador de cafe", "coador"] },
  { name: "Chá", category: A, aliases: ["cha"] },
  { name: "Achocolatado", category: A, aliases: ["nescau", "toddy", "chocolate em po"] },
  { name: "Cappuccino", category: A },
  // Laticínios / frios / ovos
  { name: "Leite", category: A },
  { name: "Leite desnatado", category: A },
  { name: "Leite sem lactose", category: A },
  { name: "Leite em pó", category: A },
  { name: "Leite condensado", category: A },
  { name: "Creme de leite", category: A },
  { name: "Iogurte", category: A },
  { name: "Requeijão", category: A, aliases: ["catupiry"] },
  { name: "Manteiga", category: A },
  { name: "Margarina", category: A },
  { name: "Queijo", category: A },
  { name: "Queijo ralado", category: A, aliases: ["parmesao"] },
  { name: "Mussarela", category: A, aliases: ["muçarela"] },
  { name: "Presunto", category: A },
  { name: "Mortadela", category: A },
  { name: "Ovos", category: A, aliases: ["ovo"] },
  // Carnes / peixes
  { name: "Carne", category: A },
  { name: "Carne moída", category: A },
  { name: "Bife", category: A },
  { name: "Frango", category: A },
  { name: "Peito de frango", category: A },
  { name: "Linguiça", category: A },
  { name: "Linguiça toscana", category: A },
  { name: "Salsicha", category: A },
  { name: "Bacon", category: A },
  { name: "Costela", category: A },
  { name: "Costelinha", category: A },
  { name: "Picanha", category: A },
  { name: "Peixe", category: A },
  { name: "Atum", category: A },
  { name: "Sardinha", category: A },
  { name: "Camarão", category: A },
  // Hortifruti
  { name: "Frutas", category: A },
  { name: "Banana", category: A },
  { name: "Maçã", category: A },
  { name: "Laranja", category: A },
  { name: "Mamão", category: A },
  { name: "Melancia", category: A },
  { name: "Uva", category: A },
  { name: "Morango", category: A },
  { name: "Abacaxi", category: A },
  { name: "Limão", category: A },
  { name: "Abacate", category: A },
  { name: "Verduras", category: A },
  { name: "Alface", category: A },
  { name: "Rúcula", category: A },
  { name: "Couve", category: A },
  { name: "Espinafre", category: A },
  { name: "Salada", category: A, aliases: ["salada pronta", "mix de folhas"] },
  { name: "Legumes", category: A },
  { name: "Batata", category: A },
  { name: "Batata doce", category: A },
  { name: "Tomate", category: A },
  { name: "Cenoura", category: A },
  { name: "Abobrinha", category: A },
  { name: "Pimentão", category: A },
  { name: "Brócolis", category: A, aliases: ["brocolis"] },
  { name: "Mandioca", category: A, aliases: ["aipim", "macaxeira"] },
  { name: "Milho", category: A },
  { name: "Milho em lata", category: A },
  { name: "Ervilha em lata", category: A },
  { name: "Azeitona", category: A },
  { name: "Palmito", category: A },
  { name: "Champignon", category: A, aliases: ["cogumelo"] },
  // Enlatados / mantimentos
  { name: "Atum em lata", category: A },
  { name: "Seleta de legumes", category: A },
  // Doces / lanches
  { name: "Chocolate", category: A },
  { name: "Bombom", category: A },
  { name: "Bala", category: A, aliases: ["bala / bombom"] },
  { name: "Chiclete", category: A },
  { name: "Pipoca", category: A, aliases: ["pipoca de microondas"] },
  { name: "Salgadinho", category: A, aliases: ["chips"] },
  { name: "Amendoim", category: A },
  { name: "Castanha", category: A },
  { name: "Mel", category: A },
  { name: "Geleia", category: A },
  { name: "Doce de leite", category: A },
  { name: "Goiabada", category: A },
  { name: "Gelatina", category: A },
  { name: "Sorvete", category: A },
  { name: "Açaí", category: A, aliases: ["acai"] },
  // Bebidas (não há categoria "Bebidas" → Alimentos)
  { name: "Suco", category: A },
  { name: "Suco de caixinha", category: A },
  { name: "Suco em pó", category: A, aliases: ["tang"] },
  { name: "Refrigerante", category: A, aliases: ["refri", "coca", "coca cola", "guarana", "pepsi"] },
  { name: "Água mineral", category: A, aliases: ["agua"] },
  { name: "Água com gás", category: A },
  { name: "Água de coco", category: A },
  { name: "Cerveja", category: A, aliases: ["breja"] },
  { name: "Cerveja sem álcool", category: A },
  { name: "Vinho", category: A },
  { name: "Espumante", category: A, aliases: ["champagne"] },
  { name: "Energético", category: A, aliases: ["red bull", "monster"] },
  { name: "Isotônico", category: A, aliases: ["gatorade", "powerade"] },
  { name: "Gelo", category: A },

  // ─────────────────── LIMPEZA ───────────────────
  { name: "Detergente", category: L, aliases: ["ype", "limpol"] },
  { name: "Lava louças", category: L, aliases: ["detergente maquina"] },
  { name: "Sabão em pó", category: L, aliases: ["omo", "sabao po"] },
  { name: "Sabão líquido", category: L },
  { name: "Sabão em barra", category: L, aliases: ["sabao de coco"] },
  { name: "Amaciante", category: L, aliases: ["downy", "comfort"] },
  { name: "Água sanitária", category: L, aliases: ["candida", "cloro"] },
  { name: "Desinfetante", category: L, aliases: ["pinho", "pinho sol"] },
  { name: "Multiuso", category: L, aliases: ["limpeza multiuso", "veja"] },
  { name: "Limpa vidro", category: L, aliases: ["limpa vidros"] },
  { name: "Lustra móveis", category: L, aliases: ["lustra moveis", "poliflor"] },
  { name: "Desengordurante", category: L },
  { name: "Limpa inox", category: L },
  { name: "Removedor", category: L },
  { name: "Cera", category: L, aliases: ["cera liquida"] },
  { name: "Álcool", category: L, aliases: ["alcool liquido"] },
  { name: "Álcool em gel", category: L, aliases: ["alcool gel"] },
  { name: "Esponja", category: L },
  { name: "Esponja de aço", category: L, aliases: ["bombril", "palha de aco"] },
  { name: "Pano de chão", category: L },
  { name: "Pano de prato", category: L },
  { name: "Pano multiuso", category: L, aliases: ["perfex"] },
  { name: "Flanela", category: L },
  { name: "Rodo", category: L },
  { name: "Vassoura", category: L },
  { name: "Pá de lixo", category: L, aliases: ["pa de lixo"] },
  { name: "Balde", category: L },
  { name: "Saco de lixo", category: L },
  { name: "Saco de lixo grande", category: L },
  { name: "Papel toalha", category: L, aliases: ["papel cozinha"] },
  { name: "Luva de borracha", category: L },
  { name: "Esfregão", category: L, aliases: ["mop"] },
  { name: "Desodorizador de ambiente", category: L, aliases: ["bom ar", "aromatizante"] },
  { name: "Inseticida", category: L, aliases: ["raid", "mata mosquito"] },
  { name: "Tira manchas", category: L, aliases: ["vanish"] },
  { name: "Alvejante", category: L },
  { name: "Sabão para roupa", category: L },

  // ─────────────────── HIGIENE ───────────────────
  { name: "Papel higiênico", category: H, aliases: ["papel hig", "papel higienico"] },
  { name: "Sabonete", category: H },
  { name: "Sabonete líquido", category: H, aliases: ["sabonete liquido"] },
  { name: "Shampoo", category: H, aliases: ["xampu"] },
  { name: "Condicionador", category: H },
  { name: "Creme para pentear", category: H },
  { name: "Creme dental", category: H, aliases: ["pasta de dente", "pasta dental"] },
  { name: "Escova de dente", category: H, aliases: ["escova dental"] },
  { name: "Fio dental", category: H },
  { name: "Enxaguante bucal", category: H, aliases: ["listerine", "antisseptico bucal"] },
  { name: "Desodorante", category: H, aliases: ["desodorante roll on", "desodorante aerosol"] },
  { name: "Absorvente", category: H },
  { name: "Protetor diário", category: H },
  { name: "Lenço umedecido", category: H },
  { name: "Lenço de papel", category: H, aliases: ["lenco de papel"] },
  { name: "Cotonete", category: H, aliases: ["haste flexivel"] },
  { name: "Algodão", category: H },
  { name: "Pente", category: H },
  { name: "Escova de cabelo", category: H },
  { name: "Lâmina de barbear", category: H, aliases: ["gilete", "aparelho de barbear"] },
  { name: "Espuma de barbear", category: H, aliases: ["gel de barbear"] },
  { name: "Hidratante", category: H, aliases: ["creme hidratante"] },
  { name: "Protetor solar", category: H, aliases: ["protetor", "filtro solar"] },
  { name: "Protetor labial", category: H },
  { name: "Perfume", category: H, aliases: ["colonia", "body splash"] },
  { name: "Esmalte", category: H },
  { name: "Acetona", category: H },
  { name: "Cortador de unha", category: H, aliases: ["alicate de unha"] },
  { name: "Talco", category: H },

  // ─────────────────── PET ───────────────────
  { name: "Ração", category: P, aliases: ["racao"] },
  { name: "Ração para cães", category: P, aliases: ["racao cachorro"] },
  { name: "Ração para gatos", category: P, aliases: ["racao gato"] },
  { name: "Areia higiênica", category: P, aliases: ["areia do gato", "areia para gato"] },
  { name: "Tapete higiênico", category: P, aliases: ["tapete pet"] },
  { name: "Petisco", category: P, aliases: ["bifinho", "snack pet"] },
  { name: "Sachê", category: P, aliases: ["sache pet"] },
  { name: "Osso para cachorro", category: P },
  { name: "Shampoo pet", category: P },
  { name: "Antipulgas", category: P, aliases: ["anti pulgas"] },
  { name: "Vermífugo", category: P, aliases: ["vermifugo pet"] },
  { name: "Coleira", category: P },
  { name: "Saquinho para fezes", category: P },

  // ─────────────────── BEBÊ ───────────────────
  { name: "Fralda", category: B },
  { name: "Lenço umedecido (bebê)", category: B, aliases: ["lenco umedecido bebe"] },
  { name: "Pomada para assadura", category: B, aliases: ["pomada", "hipoglos"] },
  { name: "Fórmula infantil", category: B, aliases: ["formula", "leite infantil"] },
  { name: "Papinha", category: B },
  { name: "Sabonete bebê", category: B },
  { name: "Shampoo bebê", category: B },
  { name: "Talco bebê", category: B },
  { name: "Mamadeira", category: B },
  { name: "Chupeta", category: B, aliases: ["bico"] },
  { name: "Cotonete bebê", category: B },

  // ─────────────────── FARMÁCIA ───────────────────
  { name: "Curativo", category: F, aliases: ["band aid", "bandeid"] },
  { name: "Álcool 70", category: F },
  { name: "Gaze", category: F },
  { name: "Esparadrapo", category: F, aliases: ["micropore"] },
  { name: "Soro fisiológico", category: F, aliases: ["soro"] },
  { name: "Termômetro", category: F, aliases: ["termometro"] },
  { name: "Analgésico", category: F, aliases: ["dipirona", "paracetamol"] },
  { name: "Anti-inflamatório", category: F, aliases: ["ibuprofeno"] },
  { name: "Antialérgico", category: F, aliases: ["antialergico", "loratadina"] },
  { name: "Antiácido", category: F, aliases: ["antiacido", "sonrisal", "eno"] },
  { name: "Pomada cicatrizante", category: F },
  { name: "Repelente", category: F, aliases: ["repelente de mosquito", "off"] },
  { name: "Vitamina C", category: F, aliases: ["vitamina"] },
  { name: "Multivitamínico", category: F, aliases: ["polivitaminico"] },
  { name: "Máscara descartável", category: F, aliases: ["mascara"] },
  { name: "Água oxigenada", category: F },
  { name: "Pastilha para garganta", category: F },
  { name: "Remédio recorrente", category: F, aliases: ["remedio de uso continuo"] },

  // ─────────────────── ESCRITÓRIO / EMPRESA ───────────────────
  { name: "Caneta", category: E },
  { name: "Lápis", category: E, aliases: ["lapis"] },
  { name: "Borracha (apagar)", category: E, aliases: ["borracha"] },
  { name: "Apontador", category: E },
  { name: "Marca texto", category: E, aliases: ["marcador de texto"] },
  { name: "Caderno", category: E },
  { name: "Bloco de notas", category: E },
  { name: "Post-it", category: E, aliases: ["bloco adesivo"] },
  { name: "Papel A4", category: E, aliases: ["folha a4", "papel sulfite", "resma"] },
  { name: "Envelope", category: E },
  { name: "Grampeador", category: E },
  { name: "Grampo", category: E },
  { name: "Clipe", category: E, aliases: ["clips"] },
  { name: "Tesoura", category: E },
  { name: "Cola", category: E, aliases: ["cola branca", "cola bastao"] },
  { name: "Fita adesiva", category: E, aliases: ["durex", "fita"] },
  { name: "Fita crepe", category: E },
  { name: "Régua", category: E, aliases: ["regua"] },
  { name: "Pasta", category: E, aliases: ["pasta plastica", "pasta arquivo"] },
  { name: "Calculadora", category: E },
  { name: "Toner", category: E, aliases: ["toner impressora"] },
  { name: "Cartucho de tinta", category: E, aliases: ["cartucho impressora"] },
  { name: "Papel para impressora", category: E },
  { name: "Quadro branco", category: E },
  { name: "Pincel para quadro", category: E, aliases: ["caneta quadro branco"] },
  { name: "Apagador", category: E },
  { name: "Crachá", category: E, aliases: ["cracha", "cordao de cracha"] },
  { name: "Mouse", category: E },
  { name: "Mousepad", category: E, aliases: ["mouse pad", "apoio de mouse"] },
  { name: "Teclado", category: E },
  { name: "Cabo USB", category: E, aliases: ["cabo usb"] },
  { name: "Copo descartável (empresa)", category: E, aliases: ["copo empresa"] },
  { name: "Água (galão)", category: E, aliases: ["galao de agua", "agua mineral galao"] },

  // ─────────────────── OUTROS (utilidades, descartáveis, churrasco, praia) ───────────────────
  // Utilidades / pilhas / iluminação
  { name: "Pilha", category: O, aliases: ["pilha aa", "pilha aaa"] },
  { name: "Lâmpada", category: O, aliases: ["lampada"] },
  { name: "Vela", category: O },
  { name: "Fósforo", category: O, aliases: ["fosforo"] },
  { name: "Isqueiro", category: O },
  { name: "Extensão", category: O, aliases: ["extensao", "filtro de linha"] },
  { name: "Filtro de água", category: O, aliases: ["vela do filtro", "refil do filtro", "refil filtro"] },
  { name: "Saco para aspirador", category: O },
  { name: "Pregador de roupa", category: O, aliases: ["prendedor de roupa"] },
  { name: "Cabide", category: O },
  { name: "Bucha de banho", category: O },
  // Cozinha (utensílios / descartáveis / embalagens)
  { name: "Papel alumínio", category: O, aliases: ["papel aluminio", "aluminio"] },
  { name: "Papel manteiga", category: O },
  { name: "Filme plástico", category: O, aliases: ["filme pvc", "rolopac", "plastico filme"] },
  { name: "Saco plástico", category: O, aliases: ["saco plastico"] },
  { name: "Saco zip", category: O, aliases: ["ziploc"] },
  { name: "Pote plástico", category: O, aliases: ["pote", "tupperware"] },
  { name: "Copo descartável", category: O },
  { name: "Prato descartável", category: O },
  { name: "Talher descartável", category: O, aliases: ["garfo descartavel", "colher descartavel"] },
  { name: "Guardanapo", category: O },
  { name: "Canudo", category: O, aliases: ["canudinho"] },
  { name: "Palito", category: O, aliases: ["palito de dente"] },
  { name: "Escumadeira", category: O },
  { name: "Concha", category: O },
  { name: "Pegador", category: O },
  { name: "Tábua de corte", category: O, aliases: ["tabua de corte"] },
  // Churrasco
  { name: "Carvão", category: O, aliases: ["carvao"] },
  { name: "Acendedor", category: O, aliases: ["acendedor de churrasqueira"] },
  { name: "Espeto de churrasco", category: O, aliases: ["espeto"] },
  { name: "Churrasqueira elétrica", category: O, aliases: ["churrasqueira eletrica"] },
  { name: "Grelha", category: O },
  // Praia / veraneio
  { name: "Toalha de praia", category: O },
  { name: "Chinelo", category: O },
  { name: "Óculos de sol", category: O, aliases: ["oculos de sol"] },
  { name: "Boia", category: O, aliases: ["boia inflavel"] },
  { name: "Guarda-sol", category: O, aliases: ["guarda sol"] },
  { name: "Cooler", category: O, aliases: ["caixa termica", "isopor"] },
];
