// =============================================================
// CATÁLOGO DE ITENS — sugestões do "teclado inteligente".
//
// Regras de ouro:
// 1. CATEGORIA sempre uma das 8 REAIS do app (genéricas, servem pra QUALQUER
//    local — casa, apê, praia, veraneio, empresa, loja, escritório):
//    Alimentos · Limpeza · Higiene · Pet · Bebê · Farmácia · Escritório / Empresa · Outros
//    (NUNCA prender um item a um local — ex.: Achocolatado é Alimentos, não "Empresa".)
// 2. `aliases` = como as pessoas DIGITAM de verdade (apelidos, marcas, variações).
//    Acento já é ignorado automaticamente na busca — não precisa repetir sem acento.
// 3. Catálogo LOCAL (sem IA/internet) = instantâneo, offline, nunca inventa.
//    Quanto mais item/apelido, mais cômodo pro usuário. Pode crescer à vontade.
// =============================================================

export type SuggestedItem = { name: string; category: string; aliases?: string[] };

// Atalhos das 8 categorias reais (evita erro de digitação no nome).
const A = "Alimentos";
const L = "Limpeza";
const H = "Higiene";
const P = "Pet";
const B = "Bebê";
const F = "Farmácia";
const E = "Escritório / Empresa";
const O = "Outros";

export const SUGGESTED_ITEMS: SuggestedItem[] = [
  // ─────────────────── ALIMENTOS ───────────────────
  // Básicos / grãos
  { name: "Arroz", category: A },
  { name: "Arroz integral", category: A },
  { name: "Feijão", category: A },
  { name: "Feijão preto", category: A },
  { name: "Feijão carioca", category: A },
  { name: "Lentilha", category: A },
  { name: "Grão de bico", category: A },
  { name: "Açúcar", category: A },
  { name: "Açúcar mascavo", category: A },
  { name: "Adoçante", category: A, aliases: ["adocante"] },
  { name: "Sal", category: A },
  { name: "Sal grosso", category: A },
  { name: "Óleo", category: A, aliases: ["oleo de soja"] },
  { name: "Azeite", category: A, aliases: ["azeite de oliva"] },
  { name: "Vinagre", category: A },
  { name: "Farinha de trigo", category: A, aliases: ["farinha"] },
  { name: "Farinha de mandioca", category: A },
  { name: "Farofa pronta", category: A, aliases: ["farofa"] },
  { name: "Fubá", category: A },
  { name: "Amido de milho", category: A, aliases: ["maizena"] },
  { name: "Aveia", category: A },
  { name: "Granola", category: A },
  { name: "Tapioca", category: A, aliases: ["goma de tapioca"] },
  { name: "Polvilho", category: A },
  // Padaria / massas
  { name: "Pão", category: A },
  { name: "Pão de forma", category: A },
  { name: "Pão francês", category: A, aliases: ["paozinho"] },
  { name: "Pão de hambúrguer", category: A },
  { name: "Pão de alho", category: A },
  { name: "Torrada", category: A },
  { name: "Bolacha água e sal", category: A, aliases: ["biscoito agua e sal", "cream cracker"] },
  { name: "Biscoito", category: A, aliases: ["bolacha"] },
  { name: "Biscoito recheado", category: A, aliases: ["bolacha recheada"] },
  { name: "Macarrão", category: A },
  { name: "Macarrão instantâneo", category: A, aliases: ["miojo", "lamen"] },
  { name: "Lasanha", category: A },
  { name: "Nhoque", category: A },
  // Molhos / temperos
  { name: "Molho de tomate", category: A, aliases: ["molho tomate"] },
  { name: "Extrato de tomate", category: A, aliases: ["massa de tomate"] },
  { name: "Maionese", category: A, aliases: ["hellmanns"] },
  { name: "Ketchup", category: A, aliases: ["catchup"] },
  { name: "Mostarda", category: A },
  { name: "Molho shoyu", category: A, aliases: ["shoyu", "molho de soja"] },
  { name: "Molho inglês", category: A },
  { name: "Vinagrete", category: A },
  { name: "Tempero pronto", category: A, aliases: ["tempero", "caldo", "knorr", "sazon"] },
  { name: "Orégano", category: A },
  { name: "Pimenta do reino", category: A, aliases: ["pimenta"] },
  { name: "Colorau", category: A, aliases: ["colorifico"] },
  { name: "Cominho", category: A },
  { name: "Canela", category: A },
  { name: "Alho", category: A },
  { name: "Cebola", category: A },
  // Café / bebidas quentes
  { name: "Café", category: A },
  { name: "Café em cápsula", category: A, aliases: ["capsula de cafe", "capsula"] },
  { name: "Filtro de café", category: A, aliases: ["filtro de papel", "filtro para cafeteira", "filtro cafeteira", "coador de cafe", "coador"] },
  { name: "Chá", category: A, aliases: ["cha"] },
  { name: "Achocolatado", category: A, aliases: ["nescau", "toddy", "chocolate em po"] },
  { name: "Cappuccino", category: A },
  // Laticínios / frios / ovos
  { name: "Leite", category: A },
  { name: "Leite desnatado", category: A },
  { name: "Leite sem lactose", category: A },
  { name: "Leite em pó", category: A },
  { name: "Leite condensado", category: A },
  { name: "Creme de leite", category: A },
  { name: "Iogurte", category: A },
  { name: "Requeijão", category: A, aliases: ["catupiry"] },
  { name: "Manteiga", category: A },
  { name: "Margarina", category: A },
  { name: "Queijo", category: A },
  { name: "Queijo ralado", category: A, aliases: ["parmesao"] },
  { name: "Mussarela", category: A, aliases: ["muçarela"] },
  { name: "Presunto", category: A },
  { name: "Mortadela", category: A },
  { name: "Ovos", category: A, aliases: ["ovo"] },
  // Carnes / peixes
  { name: "Carne", category: A },
  { name: "Carne moída", category: A },
  { name: "Bife", category: A },
  { name: "Frango", category: A },
  { name: "Peito de frango", category: A },
  { name: "Linguiça", category: A },
  { name: "Linguiça toscana", category: A },
  { name: "Salsicha", category: A },
  { name: "Bacon", category: A },
  { name: "Costela", category: A },
  { name: "Costelinha", category: A },
  { name: "Picanha", category: A },
  { name: "Peixe", category: A },
  { name: "Atum", category: A },
  { name: "Sardinha", category: A },
  { name: "Camarão", category: A },
  // Hortifruti
  { name: "Frutas", category: A },
  { name: "Banana", category: A },
  { name: "Maçã", category: A },
  { name: "Laranja", category: A },
  { name: "Mamão", category: A },
  { name: "Melancia", category: A },
  { name: "Uva", category: A },
  { name: "Morango", category: A },
  { name: "Abacaxi", category: A },
  { name: "Limão", category: A },
  { name: "Abacate", category: A },
  { name: "Verduras", category: A },
  { name: "Alface", category: A },
  { name: "Rúcula", category: A },
  { name: "Couve", category: A },
  { name: "Espinafre", category: A },
  { name: "Salada", category: A, aliases: ["salada pronta", "mix de folhas"] },
  { name: "Legumes", category: A },
  { name: "Batata", category: A },
  { name: "Batata doce", category: A },
  { name: "Tomate", category: A },
  { name: "Cenoura", category: A },
  { name: "Abobrinha", category: A },
  { name: "Pimentão", category: A },
  { name: "Brócolis", category: A, aliases: ["brocolis"] },
  { name: "Mandioca", category: A, aliases: ["aipim", "macaxeira"] },
  { name: "Milho", category: A },
  { name: "Milho em lata", category: A },
  { name: "Ervilha em lata", category: A },
  { name: "Azeitona", category: A },
  { name: "Palmito", category: A },
  { name: "Champignon", category: A, aliases: ["cogumelo"] },
  // Enlatados / mantimentos
  { name: "Atum em lata", category: A },
  { name: "Seleta de legumes", category: A },
  // Doces / lanches
  { name: "Chocolate", category: A },
  { name: "Bombom", category: A },
  { name: "Bala", category: A, aliases: ["bala / bombom"] },
  { name: "Chiclete", category: A },
  { name: "Pipoca", category: A, aliases: ["pipoca de microondas"] },
  { name: "Salgadinho", category: A, aliases: ["chips"] },
  { name: "Amendoim", category: A },
  { name: "Castanha", category: A },
  { name: "Mel", category: A },
  { name: "Geleia", category: A },
  { name: "Doce de leite", category: A },
  { name: "Goiabada", category: A },
  { name: "Gelatina", category: A },
  { name: "Sorvete", category: A },
  { name: "Açaí", category: A, aliases: ["acai"] },
  // Bebidas (não há categoria "Bebidas" → Alimentos)
  { name: "Suco", category: A },
  { name: "Suco de caixinha", category: A },
  { name: "Suco em pó", category: A, aliases: ["tang"] },
  { name: "Refrigerante", category: A, aliases: ["refri", "coca", "coca cola", "guarana", "pepsi"] },
  { name: "Água mineral", category: A, aliases: ["agua"] },
  { name: "Água com gás", category: A },
  { name: "Água de coco", category: A },
  { name: "Cerveja", category: A, aliases: ["breja"] },
  { name: "Cerveja sem álcool", category: A },
  { name: "Vinho", category: A },
  { name: "Espumante", category: A, aliases: ["champagne"] },
  { name: "Energético", category: A, aliases: ["red bull", "monster"] },
  { name: "Isotônico", category: A, aliases: ["gatorade", "powerade"] },
  { name: "Gelo", category: A },

  // ─────────────────── LIMPEZA ───────────────────
  { name: "Detergente", category: L, aliases: ["ype", "limpol"] },
  { name: "Lava louças", category: L, aliases: ["detergente maquina"] },
  { name: "Sabão em pó", category: L, aliases: ["omo", "sabao po"] },
  { name: "Sabão líquido", category: L },
  { name: "Sabão em barra", category: L, aliases: ["sabao de coco"] },
  { name: "Amaciante", category: L, aliases: ["downy", "comfort"] },
  { name: "Água sanitária", category: L, aliases: ["candida", "cloro"] },
  { name: "Desinfetante", category: L, aliases: ["pinho", "pinho sol"] },
  { name: "Multiuso", category: L, aliases: ["limpeza multiuso", "veja"] },
  { name: "Limpa vidro", category: L, aliases: ["limpa vidros"] },
  { name: "Lustra móveis", category: L, aliases: ["lustra moveis", "poliflor"] },
  { name: "Desengordurante", category: L },
  { name: "Limpa inox", category: L },
  { name: "Removedor", category: L },
  { name: "Cera", category: L, aliases: ["cera liquida"] },
  { name: "Álcool", category: L, aliases: ["alcool liquido"] },
  { name: "Álcool em gel", category: L, aliases: ["alcool gel"] },
  { name: "Esponja", category: L },
  { name: "Esponja de aço", category: L, aliases: ["bombril", "palha de aco"] },
  { name: "Pano de chão", category: L },
  { name: "Pano de prato", category: L },
  { name: "Pano multiuso", category: L, aliases: ["perfex"] },
  { name: "Flanela", category: L },
  { name: "Rodo", category: L },
  { name: "Vassoura", category: L },
  { name: "Pá de lixo", category: L, aliases: ["pa de lixo"] },
  { name: "Balde", category: L },
  { name: "Saco de lixo", category: L },
  { name: "Saco de lixo grande", category: L },
  { name: "Papel toalha", category: L, aliases: ["papel cozinha"] },
  { name: "Luva de borracha", category: L },
  { name: "Esfregão", category: L, aliases: ["mop"] },
  { name: "Desodorizador de ambiente", category: L, aliases: ["bom ar", "aromatizante"] },
  { name: "Inseticida", category: L, aliases: ["raid", "mata mosquito"] },
  { name: "Tira manchas", category: L, aliases: ["vanish"] },
  { name: "Alvejante", category: L },
  { name: "Sabão para roupa", category: L },

  // ─────────────────── HIGIENE ───────────────────
  { name: "Papel higiênico", category: H, aliases: ["papel hig", "papel higienico"] },
  { name: "Sabonete", category: H },
  { name: "Sabonete líquido", category: H, aliases: ["sabonete liquido"] },
  { name: "Shampoo", category: H, aliases: ["xampu"] },
  { name: "Condicionador", category: H },
  { name: "Creme para pentear", category: H },
  { name: "Creme dental", category: H, aliases: ["pasta de dente", "pasta dental"] },
  { name: "Escova de dente", category: H, aliases: ["escova dental"] },
  { name: "Fio dental", category: H },
  { name: "Enxaguante bucal", category: H, aliases: ["listerine", "antisseptico bucal"] },
  { name: "Desodorante", category: H, aliases: ["desodorante roll on", "desodorante aerosol"] },
  { name: "Absorvente", category: H },
  { name: "Protetor diário", category: H },
  { name: "Lenço umedecido", category: H },
  { name: "Lenço de papel", category: H, aliases: ["lenco de papel"] },
  { name: "Cotonete", category: H, aliases: ["haste flexivel"] },
  { name: "Algodão", category: H },
  { name: "Pente", category: H },
  { name: "Escova de cabelo", category: H },
  { name: "Lâmina de barbear", category: H, aliases: ["gilete", "aparelho de barbear"] },
  { name: "Espuma de barbear", category: H, aliases: ["gel de barbear"] },
  { name: "Hidratante", category: H, aliases: ["creme hidratante"] },
  { name: "Protetor solar", category: H, aliases: ["protetor", "filtro solar"] },
  { name: "Protetor labial", category: H },
  { name: "Perfume", category: H, aliases: ["colonia", "body splash"] },
  { name: "Esmalte", category: H },
  { name: "Acetona", category: H },
  { name: "Cortador de unha", category: H, aliases: ["alicate de unha"] },
  { name: "Talco", category: H },

  // ─────────────────── PET ───────────────────
  { name: "Ração", category: P, aliases: ["racao"] },
  { name: "Ração para cães", category: P, aliases: ["racao cachorro"] },
  { name: "Ração para gatos", category: P, aliases: ["racao gato"] },
  { name: "Areia higiênica", category: P, aliases: ["areia do gato", "areia para gato"] },
  { name: "Tapete higiênico", category: P, aliases: ["tapete pet"] },
  { name: "Petisco", category: P, aliases: ["bifinho", "snack pet"] },
  { name: "Sachê", category: P, aliases: ["sache pet"] },
  { name: "Osso para cachorro", category: P },
  { name: "Shampoo pet", category: P },
  { name: "Antipulgas", category: P, aliases: ["anti pulgas"] },
  { name: "Vermífugo", category: P, aliases: ["vermifugo pet"] },
  { name: "Coleira", category: P },
  { name: "Saquinho para fezes", category: P },

  // ─────────────────── BEBÊ ───────────────────
  { name: "Fralda", category: B },
  { name: "Lenço umedecido (bebê)", category: B, aliases: ["lenco umedecido bebe"] },
  { name: "Pomada para assadura", category: B, aliases: ["pomada", "hipoglos"] },
  { name: "Fórmula infantil", category: B, aliases: ["formula", "leite infantil"] },
  { name: "Papinha", category: B },
  { name: "Sabonete bebê", category: B },
  { name: "Shampoo bebê", category: B },
  { name: "Talco bebê", category: B },
  { name: "Mamadeira", category: B },
  { name: "Chupeta", category: B, aliases: ["bico"] },
  { name: "Cotonete bebê", category: B },

  // ─────────────────── FARMÁCIA ───────────────────
  { name: "Curativo", category: F, aliases: ["band aid", "bandeid"] },
  { name: "Álcool 70", category: F },
  { name: "Gaze", category: F },
  { name: "Esparadrapo", category: F, aliases: ["micropore"] },
  { name: "Soro fisiológico", category: F, aliases: ["soro"] },
  { name: "Termômetro", category: F, aliases: ["termometro"] },
  { name: "Analgésico", category: F, aliases: ["dipirona", "paracetamol"] },
  { name: "Anti-inflamatório", category: F, aliases: ["ibuprofeno"] },
  { name: "Antialérgico", category: F, aliases: ["antialergico", "loratadina"] },
  { name: "Antiácido", category: F, aliases: ["antiacido", "sonrisal", "eno"] },
  { name: "Pomada cicatrizante", category: F },
  { name: "Repelente", category: F, aliases: ["repelente de mosquito", "off"] },
  { name: "Vitamina C", category: F, aliases: ["vitamina"] },
  { name: "Multivitamínico", category: F, aliases: ["polivitaminico"] },
  { name: "Máscara descartável", category: F, aliases: ["mascara"] },
  { name: "Água oxigenada", category: F },
  { name: "Pastilha para garganta", category: F },
  { name: "Remédio recorrente", category: F, aliases: ["remedio de uso continuo"] },

  // ─────────────────── ESCRITÓRIO / EMPRESA ───────────────────
  { name: "Caneta", category: E },
  { name: "Lápis", category: E, aliases: ["lapis"] },
  { name: "Borracha (apagar)", category: E, aliases: ["borracha"] },
  { name: "Apontador", category: E },
  { name: "Marca texto", category: E, aliases: ["marcador de texto"] },
  { name: "Caderno", category: E },
  { name: "Bloco de notas", category: E },
  { name: "Post-it", category: E, aliases: ["bloco adesivo"] },
  { name: "Papel A4", category: E, aliases: ["folha a4", "papel sulfite", "resma"] },
  { name: "Envelope", category: E },
  { name: "Grampeador", category: E },
  { name: "Grampo", category: E },
  { name: "Clipe", category: E, aliases: ["clips"] },
  { name: "Tesoura", category: E },
  { name: "Cola", category: E, aliases: ["cola branca", "cola bastao"] },
  { name: "Fita adesiva", category: E, aliases: ["durex", "fita"] },
  { name: "Fita crepe", category: E },
  { name: "Régua", category: E, aliases: ["regua"] },
  { name: "Pasta", category: E, aliases: ["pasta plastica", "pasta arquivo"] },
  { name: "Calculadora", category: E },
  { name: "Toner", category: E, aliases: ["toner impressora"] },
  { name: "Cartucho de tinta", category: E, aliases: ["cartucho impressora"] },
  { name: "Papel para impressora", category: E },
  { name: "Quadro branco", category: E },
  { name: "Pincel para quadro", category: E, aliases: ["caneta quadro branco"] },
  { name: "Apagador", category: E },
  { name: "Crachá", category: E, aliases: ["cracha", "cordao de cracha"] },
  { name: "Mouse", category: E },
  { name: "Mousepad", category: E, aliases: ["mouse pad", "apoio de mouse"] },
  { name: "Teclado", category: E },
  { name: "Cabo USB", category: E, aliases: ["cabo usb"] },
  { name: "Copo descartável (empresa)", category: E, aliases: ["copo empresa"] },
  { name: "Água (galão)", category: E, aliases: ["galao de agua", "agua mineral galao"] },

  // ─────────────────── OUTROS (utilidades, descartáveis, churrasco, praia) ───────────────────
  // Utilidades / pilhas / iluminação
  { name: "Pilha", category: O, aliases: ["pilha aa", "pilha aaa"] },
  { name: "Lâmpada", category: O, aliases: ["lampada"] },
  { name: "Vela", category: O },
  { name: "Fósforo", category: O, aliases: ["fosforo"] },
  { name: "Isqueiro", category: O },
  { name: "Extensão", category: O, aliases: ["extensao", "filtro de linha"] },
  { name: "Filtro de água", category: O, aliases: ["vela do filtro", "refil do filtro", "refil filtro"] },
  { name: "Saco para aspirador", category: O },
  { name: "Pregador de roupa", category: O, aliases: ["prendedor de roupa"] },
  { name: "Cabide", category: O },
  { name: "Bucha de banho", category: O },
  // Cozinha (utensílios / descartáveis / embalagens)
  { name: "Papel alumínio", category: O, aliases: ["papel aluminio", "aluminio"] },
  { name: "Papel manteiga", category: O },
  { name: "Filme plástico", category: O, aliases: ["filme pvc", "rolopac", "plastico filme"] },
  { name: "Saco plástico", category: O, aliases: ["saco plastico"] },
  { name: "Saco zip", category: O, aliases: ["ziploc"] },
  { name: "Pote plástico", category: O, aliases: ["pote", "tupperware"] },
  { name: "Copo descartável", category: O },
  { name: "Prato descartável", category: O },
  { name: "Talher descartável", category: O, aliases: ["garfo descartavel", "colher descartavel"] },
  { name: "Guardanapo", category: O },
  { name: "Canudo", category: O, aliases: ["canudinho"] },
  { name: "Palito", category: O, aliases: ["palito de dente"] },
  { name: "Escumadeira", category: O },
  { name: "Concha", category: O },
  { name: "Pegador", category: O },
  { name: "Tábua de corte", category: O, aliases: ["tabua de corte"] },
  // Churrasco
  { name: "Carvão", category: O, aliases: ["carvao"] },
  { name: "Acendedor", category: O, aliases: ["acendedor de churrasqueira"] },
  { name: "Espeto de churrasco", category: O, aliases: ["espeto"] },
  { name: "Churrasqueira elétrica", category: O, aliases: ["churrasqueira eletrica"] },
  { name: "Grelha", category: O },
  // Praia / veraneio
  { name: "Toalha de praia", category: O },
  { name: "Chinelo", category: O },
  { name: "Óculos de sol", category: O, aliases: ["oculos de sol"] },
  { name: "Boia", category: O, aliases: ["boia inflavel"] },
  { name: "Guarda-sol", category: O, aliases: ["guarda sol"] },
  { name: "Cooler", category: O, aliases: ["caixa termica", "isopor"] },

  // ═══════════ EXPANSÃO: empresa / papelaria / copa / veraneio / chácara ═══════════

  // ── Escritório / papelaria (E) ──
  { name: "Lapiseira", category: E },
  { name: "Grafite", category: E, aliases: ["grafite lapiseira"] },
  { name: "Corretivo", category: E, aliases: ["branquinho", "corretivo liquido"] },
  { name: "Cola em bastão", category: E, aliases: ["cola bastao"] },
  { name: "Cola quente", category: E, aliases: ["refil cola quente", "bastao de cola"] },
  { name: "Estilete", category: E },
  { name: "Furador", category: E, aliases: ["perfurador"] },
  { name: "Pasta AZ", category: E, aliases: ["pasta az", "pasta registradora"] },
  { name: "Pasta suspensa", category: E },
  { name: "Caixa arquivo", category: E, aliases: ["caixa box", "caixa organizadora"] },
  { name: "Etiqueta adesiva", category: E, aliases: ["etiqueta"] },
  { name: "Carimbo", category: E },
  { name: "Tinta para carimbo", category: E, aliases: ["almofada de carimbo"] },
  { name: "Elástico", category: E, aliases: ["liga elastica"] },
  { name: "Clips bailarina", category: E, aliases: ["bailarina"] },
  { name: "Percevejo", category: E, aliases: ["tachinha", "alfinete de mapa"] },
  { name: "Barbante", category: E },
  { name: "Fita dupla face", category: E },
  { name: "Fita de embalagem", category: E, aliases: ["fita marrom", "fita larga"] },
  { name: "Espiral para encadernação", category: E, aliases: ["espiral"] },
  { name: "Capa para encadernação", category: E },
  { name: "Porta-canetas", category: E, aliases: ["porta caneta"] },
  { name: "Organizador de mesa", category: E },
  { name: "Bandeja de documentos", category: E },
  { name: "Agenda", category: E, aliases: ["planner"] },
  { name: "Calendário de mesa", category: E, aliases: ["calendario"] },
  { name: "Pen drive", category: E, aliases: ["pendrive"] },
  { name: "HD externo", category: E, aliases: ["ssd externo"] },
  { name: "Cartão de memória", category: E, aliases: ["cartao sd"] },
  { name: "Pilha 9V", category: E },
  { name: "Adaptador de tomada", category: E, aliases: ["benjamim", "te tomada"] },
  { name: "Régua de tomada", category: E, aliases: ["regua de energia"] },
  { name: "Papel kraft", category: E, aliases: ["papel pardo"] },
  { name: "Plástico bolha", category: E, aliases: ["plastico bolha"] },
  { name: "Bloco de recados", category: E },

  // ── Copa / cozinha empresa (mix) ──
  { name: "Mexedor de café", category: O, aliases: ["mexedor", "palito de cafe"] },
  { name: "Copo 200ml", category: O, aliases: ["copo de agua descartavel"] },
  { name: "Copo 50ml", category: O, aliases: ["copo de cafe descartavel", "copinho de cafe"] },
  { name: "Garrafa térmica", category: O, aliases: ["garrafa termica"] },
  { name: "Açucareiro", category: O },
  { name: "Bandeja", category: O },
  { name: "Jarra", category: O },
  { name: "Squeeze", category: O, aliases: ["garrafinha de agua"] },
  { name: "Papel toalha interfolha", category: L, aliases: ["toalha interfolha", "papel interfolhado"] },
  { name: "Refil de sabonete líquido", category: H, aliases: ["refil sabonete"] },
  { name: "Refil de álcool gel", category: L, aliases: ["refil alcool gel"] },

  // ── Limpeza (mais) ──
  { name: "Saponáceo", category: L, aliases: ["sapolio"] },
  { name: "Desentupidor", category: L, aliases: ["bomba desentupidora"] },
  { name: "Soda cáustica", category: L, aliases: ["soda caustica"] },
  { name: "Detergente neutro", category: L },
  { name: "Pano de microfibra", category: L, aliases: ["microfibra"] },
  { name: "Escova sanitária", category: L, aliases: ["escova de vaso", "piacaba"] },
  { name: "Pastilha sanitária", category: L, aliases: ["bloco sanitario", "pedra sanitaria"] },
  { name: "Lava roupas líquido", category: L, aliases: ["sabao liquido para roupa"] },
  { name: "Tira limo", category: L },
  { name: "Limpa estofado", category: L, aliases: ["limpa carpete"] },
  { name: "Espanador", category: L },
  { name: "Cera líquida", category: L, aliases: ["cera para piso"] },

  // ── Descartáveis (mais) ──
  { name: "Marmitex", category: O, aliases: ["marmita", "marmita de aluminio"] },
  { name: "Pote para viagem", category: O, aliases: ["pote delivery", "embalagem delivery"] },
  { name: "Touca descartável", category: O, aliases: ["touca descartavel"] },
  { name: "Luva descartável", category: O, aliases: ["luva plastica"] },
  { name: "Forminha de doce", category: O, aliases: ["forminha"] },
  { name: "Vela de aniversário", category: O, aliases: ["vela aniversario"] },
  { name: "Toalha de mesa descartável", category: O, aliases: ["toalha plastica de mesa"] },
  { name: "Sacola plástica", category: O, aliases: ["sacola"] },
  { name: "Saco para freezer", category: O, aliases: ["saco freezer"] },
  { name: "Saco kraft", category: O, aliases: ["saco de papel"] },

  // ── Utilitários do dia a dia / ferragens (O) ──
  { name: "Fita isolante", category: O },
  { name: "Fita veda rosca", category: O, aliases: ["veda rosca"] },
  { name: "Cola epóxi", category: O, aliases: ["durepoxi", "massa epoxi"] },
  { name: "Super cola", category: O, aliases: ["super bonder", "cola instantanea"] },
  { name: "Parafuso", category: O },
  { name: "Prego", category: O },
  { name: "Bucha para parede", category: O, aliases: ["bucha de parede"] },
  { name: "Lixa", category: O },
  { name: "Trena", category: O, aliases: ["fita metrica"] },
  { name: "Martelo", category: O },
  { name: "Chave de fenda", category: O, aliases: ["chave philips"] },
  { name: "Alicate", category: O },
  { name: "Abraçadeira", category: O, aliases: ["enforca gato"] },
  { name: "Corda", category: O, aliases: ["corda de varal"] },
  { name: "Cadeado", category: O },
  { name: "Pilha recarregável", category: O, aliases: ["pilha recarregavel"] },
  { name: "Lâmpada LED", category: O, aliases: ["lampada led"] },
  { name: "Fita LED", category: O, aliases: ["fita de led"] },
  { name: "Lanterna", category: O },
  { name: "Power bank", category: O, aliases: ["carregador portatil", "bateria externa"] },
  { name: "Tomada", category: O, aliases: ["interruptor"] },

  // ── Veraneio / praia (O) ──
  { name: "Bronzeador", category: O },
  { name: "Pós-sol", category: O, aliases: ["pos sol", "hidratante pos sol"] },
  { name: "Cadeira de praia", category: O },
  { name: "Canga", category: O },
  { name: "Esteira de praia", category: O, aliases: ["esteira"] },
  { name: "Bola", category: O, aliases: ["bola de praia"] },
  { name: "Raquete de frescobol", category: O, aliases: ["frescobol"] },
  { name: "Necessaire", category: O },
  { name: "Toalha de banho", category: O },
  { name: "Lençol", category: O, aliases: ["lencol"] },
  { name: "Fronha", category: O },
  { name: "Travesseiro", category: O },
  { name: "Cobertor", category: O, aliases: ["manta"] },
  { name: "Lampião", category: O, aliases: ["lampiao", "luminaria de camping"] },

  // ── Chácara / jardim / piscina (O) ──
  { name: "Mangueira de jardim", category: O, aliases: ["mangueira"] },
  { name: "Regador", category: O },
  { name: "Pá de jardim", category: O, aliases: ["pa de jardinagem"] },
  { name: "Enxada", category: O },
  { name: "Rastelo", category: O, aliases: ["ancinho"] },
  { name: "Tesoura de poda", category: O },
  { name: "Sementes", category: O, aliases: ["semente"] },
  { name: "Adubo", category: O, aliases: ["fertilizante"] },
  { name: "Terra adubada", category: O, aliases: ["terra vegetal"] },
  { name: "Vaso de planta", category: O, aliases: ["vaso"] },
  { name: "Veneno de formiga", category: O, aliases: ["formicida", "mata formiga"] },
  { name: "Cloro para piscina", category: O, aliases: ["cloro piscina"] },
  { name: "Pastilha de cloro", category: O },
  { name: "Algicida", category: O, aliases: ["anti alga"] },
  { name: "Clarificante", category: O, aliases: ["decantador piscina"] },
  { name: "Peneira de piscina", category: O, aliases: ["peneira"] },
  { name: "Lenha", category: O },
  // ─── Expansao jun/2026 — mais usados BR + apelidos/erros comuns ───
  { name: "Peixe congelado", category: A, aliases: ["peixe", "filé de peixe"] },
  { name: "Frango congelado", category: A, aliases: ["frango"] },
  { name: "Carne congelada", category: A, aliases: ["carne"] },
  { name: "Hambúrguer", category: A, aliases: ["burger", "hamburger"] },
  { name: "Almôndega", category: A, aliases: ["almôndegas"] },
  { name: "Nuggets", category: A, aliases: ["naguets", "nuggets de frango", "naget"] },
  { name: "Empanado de frango", category: A, aliases: ["empanado", "frango empanado"] },
  { name: "Pizza congelada", category: A, aliases: ["pizza", "piza"] },
  { name: "Pastel", category: A, aliases: ["pasteu"] },
  { name: "Coxinha", category: A, aliases: ["cuxinha"] },
  { name: "Salgado congelado", category: A, aliases: ["salgadinho congelado", "salgados"] },
  { name: "Legumes congelados", category: A, aliases: ["legume congelado", "seleta de legumes"] },
  { name: "Brócolis congelado", category: A, aliases: ["brocolis", "brócoli"] },
  { name: "Ervilha congelada", category: A, aliases: ["ervilha"] },
  { name: "Fruta congelada", category: A, aliases: ["frutas congeladas", "polpa de fruta"] },
  { name: "Açaí congelado", category: A, aliases: ["acai", "polpa de açaí"] },
  { name: "Ovos de codorna", category: A, aliases: ["ovo de codorna", "codorna"] },
  { name: "Iogurte natural", category: A, aliases: ["iogurte", "yogurte", "iorgute"] },
  { name: "Iogurte grego", category: A, aliases: ["yogurte grego", "grego"] },
  { name: "Bebida láctea", category: A, aliases: ["toddynho", "iogurte de beber"] },
  { name: "Danoninho / petit suisse", category: A, aliases: ["danoninho", "petit suisse", "danone", "queijinho"] },
  { name: "Kefir", category: A, aliases: ["kefyr", "quefir"] },
  { name: "Catupiry", category: A, aliases: ["catupiri", "requeijão catupiry"] },
  { name: "Cream cheese", category: A, aliases: ["crime chis", "creme cheese", "philadelphia"] },
  { name: "Ricota", category: A, aliases: ["riccota"] },
  { name: "Queijo prato", category: A, aliases: ["queijo prato fatiado", "prato"] },
  { name: "Queijo minas frescal", category: A, aliases: ["queijo minas", "minas frescal", "queijo branco"] },
  { name: "Queijo coalho", category: A, aliases: ["queijo de coalho", "queijo coalo"] },
  { name: "Queijo mussarela", category: A, aliases: ["mussarela", "muçarela", "mozzarella", "mozarela"] },
  { name: "Queijo parmesão", category: A, aliases: ["parmesao", "parmesão ralado", "queijo ralado", "parmegiano"] },
  { name: "Queijo gorgonzola", category: A, aliases: ["gorgonzola", "queijo azul"] },
  { name: "Queijo cheddar", category: A, aliases: ["cheddar", "chedar", "cheedar"] },
  { name: "Queijo provolone", category: A, aliases: ["provolone", "provolone defumado"] },
  { name: "Peito de peru", category: A, aliases: ["peito de peru fatiado", "peru"] },
  { name: "Salmão", category: A, aliases: ["salmão fresco", "salmon"] },
  { name: "Tilápia", category: A, aliases: ["filé de tilápia"] },
  { name: "Merluza", category: A, aliases: ["merluza congelada"] },
  { name: "Lula", category: A, aliases: ["anéis de lula", "lula limpa"] },
  { name: "Bacalhau", category: A, aliases: ["bacalhao", "bacalhau dessalgado"] },
  { name: "Sobrecoxa de frango", category: A, aliases: ["sobrecoxa", "sobre coxa"] },
  { name: "Coxa de frango", category: A, aliases: ["coxa", "coxas"] },
  { name: "Asa de frango", category: A, aliases: ["asinha", "asa", "tulipa de frango"] },
  { name: "Patinho", category: A, aliases: ["patinho moído", "carne patinho"] },
  { name: "Coxão mole", category: A, aliases: ["coxão"] },
  { name: "Acém", category: A, aliases: ["carne acém"] },
  { name: "Alcatra", category: A, aliases: ["alcatra peça"] },
  { name: "Contrafilé", category: A, aliases: ["contra filé"] },
  { name: "Filé mignon", category: A, aliases: ["filé minhão", "mignon"] },
  { name: "Maminha", category: A, aliases: ["maminha de alcatra"] },
  { name: "Fraldinha", category: A, aliases: ["fraldinha bovina"] },
  { name: "Músculo", category: A, aliases: ["músculo bovino"] },
  { name: "Costela bovina", category: A, aliases: ["costela", "costela boi"] },
  { name: "Cupim", category: A, aliases: ["cupim bovino"] },
  { name: "Carne seca", category: A, aliases: ["charque", "carne de sol", "jabá"] },
  { name: "Pernil", category: A, aliases: ["pernil suíno"] },
  { name: "Lombo", category: A, aliases: ["lombo suíno", "lombo de porco"] },
  { name: "Costela suína", category: A, aliases: ["costelinha de porco", "costela de porco"] },
  { name: "Agrião", category: A },
  { name: "Beterraba", category: A, aliases: ["betraba", "betarraba"] },
  { name: "Repolho", category: A, aliases: ["repolho verde", "repolo"] },
  { name: "Alho-poró", category: A, aliases: ["alho poro", "poró"] },
  { name: "Abóbora", category: A, aliases: ["jerimum", "moranga", "abóbora cabotiá"] },
  { name: "Chuchu", category: A, aliases: ["xuxu"] },
  { name: "Quiabo", category: A, aliases: ["quiabos", "kiabo"] },
  { name: "Berinjela", category: A, aliases: ["beringela", "berinjela roxa"] },
  { name: "Melão", category: A },
  { name: "Goiaba", category: A, aliases: ["goiba", "goiaba vermelha"] },
  { name: "Manga", category: A, aliases: ["manga palmer", "manga tommy", "mango"] },
  { name: "Pêssego", category: A, aliases: ["pêssegos"] },
  { name: "Ameixa", category: A, aliases: ["ameixa preta", "ameicha"] },
  { name: "Kiwi", category: A, aliases: ["quiui", "kiui"] },
  { name: "Caqui", category: A, aliases: ["kaki"] },
  { name: "Maçã verde", category: A, aliases: ["maçã granny"] },
  { name: "Tangerina", category: A, aliases: ["mexerica", "bergamota", "ponkan", "mexirica", "poncã"] },
  { name: "Açúcar cristal", category: A, aliases: ["açúcar"] },
  { name: "Açúcar demerara", category: A, aliases: ["demerara", "demerara mascavo"] },
  { name: "Biscoito doce", category: A, aliases: ["bolacha doce", "biscoito recheado", "biscoito"] },
  { name: "Biscoito integral", category: A, aliases: ["bolacha integral"] },
  { name: "Cereal matinal", category: A, aliases: ["sucrilhos", "cereal", "cereal integral", "granola"] },
  { name: "Mistura para bolo", category: A, aliases: ["mistura de bolo", "bolo de caixinha", "massa de bolo"] },
  { name: "Castanha de caju", category: A, aliases: ["castanha caju", "caju"] },
  { name: "Castanha-do-pará", category: A, aliases: ["castanha do para", "castanha do brasil"] },
  { name: "Nozes", category: A, aliases: ["noz", "noz torrada", "núzes"] },
  { name: "Amêndoa", category: A, aliases: ["amêndoas", "amêndoa torrada"] },
  { name: "Uva passa", category: A, aliases: ["uva-passa", "passas", "uvas passas"] },
  { name: "Coco ralado", category: A, aliases: ["coco ralado em pacote"] },
  { name: "Leite de coco", category: A, aliases: ["leite coco"] },
  { name: "Óleo de coco", category: A },
  { name: "Pasta de amendoim", category: A, aliases: ["pasta amendoim", "peanut butter", "manteiga de amendoim"] },
  { name: "Suco de laranja", category: A, aliases: ["suco laranja", "laranja natural"] },
  { name: "Suco de uva", category: A, aliases: ["suco uva", "suco de uva integral"] },
  { name: "Suco concentrado", category: A, aliases: ["suco em garrafa", "concentrado", "suco maguary"] },
  { name: "Refresco em pó", category: A, aliases: ["suco em pó", "tang", "refresco", "suco de pozinho", "clight"] },
  { name: "Chá verde", category: A, aliases: ["chá-verde"] },
  { name: "Chá preto", category: A },
  { name: "Chá de camomila", category: A, aliases: ["camomila"] },
  { name: "Erva-mate", category: A, aliases: ["erva mate", "mate", "chimarrão", "tererê"] },
  { name: "Café solúvel", category: A, aliases: ["nescafé", "café instantâneo"] },
  { name: "Achocolatado em pó", category: A, aliases: ["achocolatado", "nescau", "toddy", "chocolate em po"] },
  { name: "Achocolatado pronto", category: A, aliases: ["toddynho", "achocolatado pronto pra beber"] },
  { name: "Bebida vegetal", category: A, aliases: ["leite vegetal", "bebida de soja", "bebida de aveia", "bebida de amêndoa", "leite de amendoas"] },
  { name: "Cacau em pó", category: A, aliases: ["cacau", "cacau 100"] },
  { name: "Chocolate em barra", category: A, aliases: ["barra de chocolate", "chocolate ao leite", "chocolate", "tablete de chocolate"] },
  { name: "Chocolate branco", category: A, aliases: ["chocolate branco em barra"] },
  { name: "Chocolate amargo", category: A, aliases: ["chocolate meio amargo", "chocolate 70", "chocolate preto", "chocolate diet"] },
  { name: "Chocolate para derreter", category: A, aliases: ["chocolate de derreter", "cobertura de chocolate", "chocolate em gotas", "gotas de chocolate", "chocolate fracionado"] },
  { name: "Granulado", category: A, aliases: ["chocolate granulado", "granulado de chocolate", "confeito"] },
  { name: "Brigadeiro pronto", category: A, aliases: ["brigadeiro", "docinho de festa"] },
  { name: "Pirulito", category: A, aliases: ["pirulitos", "piruliro"] },
  { name: "Barra de cereal", category: A, aliases: ["barra de granola", "barrinha de cereal", "barrinha"] },
  { name: "Picolé", category: A, aliases: ["sorvete de palito", "sacolé"] },
  { name: "Pudim", category: A, aliases: ["pudim de leite", "mistura para pudim", "pudim de chocolate"] },
  { name: "Chantilly", category: A, aliases: ["chantily", "chantilly spray", "creme chantilly"] },
  { name: "Paçoca", category: A, aliases: ["paçoquinha"] },
  { name: "Cocada", category: A, aliases: ["cocada branca"] },
  { name: "Pé de moleque", category: A, aliases: ["pé-de-moleque"] },
  { name: "Rapadura", category: A, aliases: ["rapadura de cana"] },
  { name: "Semente de chia", category: A, aliases: ["chia", "sementes de chia"] },
  { name: "Linhaça", category: A, aliases: ["semente de linhaça", "linhaça dourada"] },
  { name: "Gergelim", category: A, aliases: ["sésamo", "semente de gergelim"] },
  { name: "Fermento químico", category: A, aliases: ["fermento em pó", "royal", "fermento de bolo"] },
  { name: "Fermento biológico", category: A, aliases: ["fermento de pão", "levedura"] },
  { name: "Essência de baunilha", category: A, aliases: ["baunilha", "extrato de baunilha"] },
  { name: "Corante alimentício", category: A, aliases: ["corante de bolo", "corante comestível"] },
  { name: "Molho de pimenta", category: A, aliases: ["pimenta molho", "tabasco", "molho de pimenta vermelha"] },
  { name: "Molho pesto", category: A, aliases: ["pesto", "molho de manjericão"] },
  { name: "Molho barbecue", category: A, aliases: ["barbecue", "molho bbq", "bbq"] },
  { name: "Patê", category: A, aliases: ["patê de atum", "patê de presunto"] },
  { name: "Conserva de cogumelo", category: A, aliases: ["cogumelo", "champignon", "champignon em conserva"] },
  { name: "Vinagre balsâmico", category: A, aliases: ["balsamico", "aceto balsâmico"] },
  { name: "Proteína de soja", category: A, aliases: ["carne de soja", "PTS", "soja texturizada"] },
  { name: "Hambúrguer vegetal", category: A, aliases: ["hamburguer vegano", "burger vegetal", "futuro burger"] },
  { name: "Feijão branco", category: A },
  { name: "Grão-de-bico", category: A, aliases: ["grao de bico", "grãodebico"] },
  { name: "Ervilha seca", category: A, aliases: ["ervilha partida"] },
  { name: "Quinoa", category: A, aliases: ["quinua", "kinoa"] },
  { name: "Milho para pipoca", category: A, aliases: ["milho de pipoca", "pipoca", "pipoca de micro-ondas"] },
  { name: "Flocão de milho", category: A, aliases: ["flocao", "cuscuz", "flocão para cuscuz"] },
  { name: "Polenta", category: A, aliases: ["polenta pronta", "polenta pré-cozida", "fubá de polenta"] },
  { name: "Trigo para quibe", category: A, aliases: ["trigo quibe", "triguilho", "trigo para kibe"] },
  { name: "Farinha de rosca", category: A, aliases: ["farinha rosca", "farinha pra empanar"] },
  { name: "Arroz branco", category: A, aliases: ["arroz", "aroz", "arroz tipo 1", "arroz agulhinha"] },
  { name: "Arroz parboilizado", category: A, aliases: ["arroz par boiled", "parboilizado"] },
  { name: "Arroz japonês", category: A, aliases: ["arroz para sushi", "arroz de sushi", "arroz cateto"] },
  { name: "Macarrão espaguete", category: A, aliases: ["espaguete", "spaghetti", "talharim"] },
  { name: "Macarrão parafuso", category: A, aliases: ["parafuso", "fusilli"] },
  { name: "Macarrão penne", category: A, aliases: ["penne", "macarrão pena"] },
  { name: "Macarrão integral", category: A },
  { name: "Massa fresca", category: A, aliases: ["massa fresca caseira", "talharim fresco"] },
  { name: "Pão integral", category: A },
  { name: "Pão de queijo", category: A, aliases: ["pão de queijo congelado"] },
  { name: "Pão sírio", category: A, aliases: ["pão árabe", "pão pita"] },
  { name: "Pão de batata", category: A, aliases: ["pão de batata recheado"] },
  { name: "Pão de mel", category: A },
  { name: "Croissant", category: A, aliases: ["croasã", "croissant congelado", "cruassã"] },
  { name: "Caldo de carne / galinha", category: A, aliases: ["caldo de galinha", "caldo de carne", "caldo knorr", "tablete de caldo", "cubo de caldo", "caldo maggi"] },
  { name: "Cebolinha", category: A, aliases: ["cebolinha verde", "cheiro verde"] },
  { name: "Salsinha", category: A, aliases: ["salsa", "salsinha picada", "cheiro verde"] },
  { name: "Coentro", category: A, aliases: ["coentro fresco", "coetro"] },
  { name: "Manjericão", category: A, aliases: ["basílico"] },
  { name: "Hortelã", category: A, aliases: ["menta"] },
  { name: "Gengibre", category: A, aliases: ["gengibre fresco", "jengibre"] },
  { name: "Açafrão / cúrcuma", category: A, aliases: ["acafrao", "cúrcuma", "açafrão da terra", "turmeric"] },
  { name: "Folha de louro", category: A, aliases: ["louro", "folhas de louro", "loro"] },
  { name: "Curry", category: A, aliases: ["curry em pó", "caril"] },
  { name: "Guaraná", category: A, aliases: ["guaraná antarctica", "refrigerante guaraná"] },
  { name: "Coca-cola", category: A, aliases: ["coca", "coca cola", "refrigerante", "refri"] },
  { name: "Água tônica", category: A, aliases: ["tônica"] },
  { name: "Cachaça", category: A, aliases: ["pinga", "aguardente", "51"] },
  { name: "Whisky", category: A, aliases: ["whiski", "uísque", "whisky escocês"] },
  { name: "Vodka", category: A, aliases: ["vodca"] },
  { name: "Gin", category: A, aliases: ["gim", "gin tônica"] },
  { name: "Sabão de coco", category: L, aliases: ["sabão em barra", "sabão de coco em barra"] },
  { name: "Naftalina / antimofo", category: L, aliases: ["naftalina", "antimofo", "anti-mofo", "bolinha de naftalina"] },
  { name: "Ração úmida", category: P, aliases: ["ração úmida em lata"] },
  { name: "Sachê para pets", category: P, aliases: ["sache", "sachê para cães", "sachê para gatos", "sachê pet"] },
  { name: "Petisco para pets", category: P, aliases: ["petisco", "bifinho", "petisco para cães", "petisco para gatos", "biscoito de cachorro"] },
  { name: "Areia para gatos", category: P, aliases: ["areia de gato", "areia sanitária", "areia aglomerante", "granulado sanitário", "areia para gato"] },
  { name: "Tapete higiênico (pet)", category: P, aliases: ["tapete higienico", "tapete pet", "pad higiênico", "tapete xixi"] },
  { name: "Shampoo para pets", category: P, aliases: ["shampoo para caes", "shampoo para gatos", "shampoo de cachorro", "shampoo pet"] },
  { name: "Vermífugo (pet)", category: P, aliases: ["vermifugo", "vermífugo para cães", "vermífugo para gatos", "vermifugo pet"] },
  { name: "Guia (pet)", category: P, aliases: ["guia", "guia de cachorro", "coleira com guia", "corda de passeio"] },
  { name: "Caixa de transporte (pet)", category: P, aliases: ["caixa de transporte", "caixa transporte pet", "caixa de viagem"] },
  { name: "Arranhador", category: P, aliases: ["arranhador para gatos", "arranhador de gato"] },
  { name: "Cama pet", category: P, aliases: ["cama de cachorro", "caminha pet", "cama para cão", "cama de gato"] },
  { name: "Comedouro", category: P, aliases: ["comedouro pet", "potinho de ração", "comedouro automático"] },
  { name: "Bebedouro (pet)", category: P, aliases: ["bebedouro pet", "bebedouro automático", "fonte para gato"] },
  { name: "Brinquedo pet", category: P, aliases: ["brinquedo de cachorro", "brinquedo para gatos", "bolinha", "mordedor pet"] },
  { name: "Saquinho de fezes", category: P, aliases: ["saquinho de cocô", "cata caca", "saco de fezes", "saquinho higiênico"] },
  { name: "Caixa de areia", category: P, aliases: ["caixa sanitária", "banheiro de gato"] },
  { name: "Pá para fezes", category: P, aliases: ["pá de gato", "pazinha de areia"] },
  { name: "Fralda de pano", category: B, aliases: ["fralda de pano para arrotar"] },
  { name: "Óleo para bebê", category: B, aliases: ["óleo infantil", "oleo de bebe", "johnsons baby"] },
  { name: "Escovinha de dentes (bebê)", category: B, aliases: ["escovinha de dentes bebê", "dedeira", "escova de dente infantil"] },
  { name: "Cereal infantil", category: B, aliases: ["mucilon", "papinha de cereal"] },
  { name: "Cobertor de bebê", category: B, aliases: ["cobertor bebe", "manta de bebê", "cobertorzinho"] },
  { name: "Banheira para bebê", category: B, aliases: ["banheira de bebe", "banheira infantil"] },
  { name: "Toalha de bebê", category: B, aliases: ["toalha para bebe", "toalha com capuz", "toalha fralda"] },
  { name: "Aspirador nasal", category: B, aliases: ["aspirador nasal infantil"] },
  { name: "Cortador de unhas (bebê)", category: B, aliases: ["cortador de unhas bebe", "cortador infantil", "tesourinha de bebê"] },
  { name: "Babador", category: B, aliases: ["babadores", "babeiro"] },
  { name: "Carrinho de bebê", category: B, aliases: ["carrinho de passeio", "carrinho"] },
  { name: "Mordedor", category: B, aliases: ["teether", "chocalho"] },
  { name: "Fralda noturna", category: B, aliases: ["fralda hiper noturna", "fralda de dormir"] },
  { name: "Probiótico", category: F, aliases: ["probioticos", "floratil"] },
  { name: "Vitamina D", category: F, aliases: ["vit d", "colecalciferol"] },
  { name: "Complexo B", category: F, aliases: ["vitamina b", "vitaminas do complexo b"] },
  { name: "Ferro", category: F, aliases: ["sulfato ferroso", "suplemento de ferro"] },
  { name: "Cálcio", category: F, aliases: ["suplemento de cálcio"] },
  { name: "Magnésio", category: F, aliases: ["cloreto de magnésio", "magnésio quelato"] },
  { name: "Ômega 3", category: F, aliases: ["ômega-3", "óleo de peixe"] },
  { name: "Polivitamínico", category: F, aliases: ["multivitamínico", "centrum"] },
  { name: "Xarope para tosse", category: F, aliases: ["xarope", "xarope expectorante", "vick xarope"] },
  { name: "Descongestionante nasal", category: F, aliases: ["sorine", "neosoro", "spray nasal"] },
  { name: "Sal de fruta / Eno", category: F, aliases: ["sal de fruta", "eno", "sal de frutas", "sonrisal"] },
  { name: "Soro de reidratação", category: F, aliases: ["soro caseiro", "floralyte", "reidratante oral"] },
  { name: "Antidiarreico", category: F, aliases: ["loperamida", "imosec", "remédio para diarreia"] },
  { name: "Dipirona", category: F, aliases: ["novalgina", "analgésico"] },
  { name: "Paracetamol", category: F, aliases: ["tylenol"] },
  { name: "Ibuprofeno", category: F, aliases: ["advil", "alivium"] },
  { name: "AAS / Aspirina", category: F, aliases: ["aspirina", "aas", "ácido acetilsalicílico", "melhoral"] },
  { name: "Buscopan", category: F, aliases: ["escopolamina", "antiespasmódico", "buscopam"] },
  { name: "Dorflex", category: F, aliases: ["relaxante muscular", "dorflexx"] },
  { name: "Termômetro digital", category: F, aliases: ["termometro"] },
  { name: "Band-aid", category: F, aliases: ["band aid", "bandeide", "curativo", "esparadrapo", "bandaid"] },
  { name: "Micropore", category: F, aliases: ["fita micropore", "esparadrapo de papel"] },
  { name: "Preservativo", category: F, aliases: ["camisinha", "camisa de vênus", "jontex"] },
  { name: "Lubrificante íntimo", category: F, aliases: ["gel lubrificante", "ky gel"] },
  { name: "Anticoncepcional", category: F, aliases: ["pílula", "pilula anticoncepcional", "contraceptivo"] },
  { name: "Teste de gravidez", category: F, aliases: ["teste de farmácia"] },
  { name: "Seringa", category: F, aliases: ["seringa descartável", "seringa e agulha"] },
  { name: "Aparelho de pressão", category: F, aliases: ["esfigmomanômetro", "medidor de pressão"] },
  { name: "Oxímetro", category: F, aliases: ["oxímetro de dedo"] },
  { name: "Shampoo anticaspa", category: H, aliases: ["anti caspa", "clear", "shampoo anti-caspa"] },
  { name: "Gel de cabelo", category: H, aliases: ["gel fixador", "gel para cabelo"] },
  { name: "Óleo capilar", category: H, aliases: ["óleo para cabelo", "óleo de argan"] },
  { name: "Tintura de cabelo", category: H, aliases: ["tinta de cabelo", "coloração", "koleston"] },
  { name: "Desodorante roll-on", category: H, aliases: ["desodorante roll on", "roll-on", "rolon", "desodorante rolon"] },
  { name: "Desodorante aerosol", category: H, aliases: ["desodorante spray", "rexona aerosol"] },
  { name: "Absorvente noturno", category: H, aliases: ["absorvente para dormir", "absorvente always noturno"] },
  { name: "Coletor menstrual", category: H, aliases: ["copo menstrual", "coletor"] },
  { name: "Disco de algodão", category: H, aliases: ["disco demaquilante", "algodão redondo"] },
  { name: "Sabonete íntimo", category: H, aliases: ["sabonete íntimo feminino", "lavanda íntima"] },
  { name: "Pincel atômico / marcador", category: E, aliases: ["pincel atômico", "marcador permanente", "marca texto", "marcador"] },
  { name: "Marca-texto", category: E, aliases: ["marca texto", "caneta marca-texto", "grifa texto", "grifador"] },
  { name: "Pincel para quadro branco", category: E, aliases: ["caneta de lousa", "marcador de quadro branco"] },
  { name: "Pilha AA", category: E, aliases: ["pilha pequena", "pilha duracel aa", "pilha grande"] },
  { name: "Pilha AAA", category: E, aliases: ["pilha palito", "pilha fina"] },
  { name: "Faca", category: O, aliases: ["facas", "faca de cozinha", "faca de chef"] },
  { name: "Garfo", category: O, aliases: ["garfos"] },
  { name: "Colher", category: O, aliases: ["colheres", "colher de sopa", "colher de pau"] },
  { name: "Talheres", category: O, aliases: ["talher", "jogo de talheres", "faqueiro"] },
  { name: "Prato", category: O, aliases: ["pratos", "prato fundo", "prato raso"] },
  { name: "Copo", category: O, aliases: ["copos", "copo de vidro", "copo americano"] },
  { name: "Caneca", category: O, aliases: ["canecas", "caneca de café"] },
  { name: "Xícara", category: O, aliases: ["xícaras", "xicra"] },
  { name: "Tigela", category: O, aliases: ["tigelas", "bowl", "tijela", "vasilha"] },
  { name: "Panela", category: O, aliases: ["panelas", "panela de pressão", "jogo de panelas"] },
  { name: "Frigideira", category: O, aliases: ["frigideiras", "frigideira antiaderente", "fritadeira"] },
  { name: "Forma para forno", category: O, aliases: ["forma de bolo", "assadeira", "forma de pizza"] },
  { name: "Tesoura de cozinha", category: O, aliases: ["tesoura"] },
  { name: "Ralador", category: O, aliases: ["ralador de queijo"] },
  { name: "Espremedor", category: O, aliases: ["espremedor de limão", "espremedor de frutas"] },
  { name: "Descascador", category: O, aliases: ["descascador de legumes", "descascador de batata", "pelador"] },
  { name: "Batedor / fouet", category: O, aliases: ["fouet", "batedor de ovos", "fuê"] },
  { name: "Peneira", category: O, aliases: ["peneira de farinha"] },
  { name: "Funil", category: O, aliases: ["funil de cozinha"] },
  { name: "Escorredor", category: O, aliases: ["escorredor de macarrão", "escorredor de louça", "escoredor"] },
  { name: "Abridor", category: O, aliases: ["abridor de lata", "abridor de garrafa", "saca-rolhas"] },
  { name: "Forma de gelo", category: O, aliases: ["forminha de gelo", "gelo"] },
  { name: "Papel filme", category: O, aliases: ["plástico filme", "filme plástico", "insulfilm de cozinha"] },
  { name: "Avental", category: O, aliases: ["avental de cozinha"] },
  { name: "Varal", category: O, aliases: ["varal de roupa", "varal de chão", "varal dobrável"] },
  { name: "Buchinha", category: O, aliases: ["bucha de banho", "bucha vegetal", "esponja de banho"] },
  { name: "Guardanapo de pano", category: O, aliases: ["guardanapo de tecido"] },
  { name: "Tapete de banheiro", category: O, aliases: ["tapete antiderrapante"] },
  { name: "Edredom", category: O, aliases: ["edredon", "colcha de inverno"] },
  { name: "Colcha", category: O, aliases: ["colcha de cama", "cobre leito"] },
  { name: "Carregador de celular", category: O, aliases: ["carregador", "fonte de carregador", "cabo carregador"] },
  { name: "Fone de ouvido", category: O, aliases: ["fone", "headphone", "earphone"] },
  { name: "Botijão de gás", category: O, aliases: ["botijão", "gás de cozinha", "gas", "p13"] },
  { name: "Repelente elétrico", category: O, aliases: ["repelente de tomada", "raid elétrico", "repelente para mosquito"] },
  { name: "Vela perfumada", category: O, aliases: ["vela aromática", "velinha"] },
  { name: "Organizador", category: O, aliases: ["caixa organizadora", "organizador de gaveta"] },
  { name: "Prendedor de roupa", category: O, aliases: ["prendedor", "pregador"] },
  { name: "Extensão / benjamim", category: O, aliases: ["extensão", "benjamim", "filtro de linha", "tomada tripla", "régua de tomada"] },
  { name: "Lona", category: O, aliases: ["lona plástica", "lona de cobertura"] },

];
